-- FANTASY BÀSQUET ALELLA · V16
-- Retrocedir jornades + valors de mercat per jugador i per entrenador/equip.

-- 1) Mercat independent dels entrenadors per entrenador + equip real.
create table if not exists public.coach_team_market (
  id bigint generated by default as identity primary key,
  coach_id bigint not null references public.coaches(id) on delete cascade,
  real_team_id bigint not null references public.real_teams(id) on delete cascade,
  current_value numeric not null default 12,
  created_at timestamptz default now(),
  unique (coach_id, real_team_id)
);

alter table public.coach_team_market enable row level security;

drop policy if exists "Lectura autenticada mercat entrenadors" on public.coach_team_market;
create policy "Lectura autenticada mercat entrenadors"
on public.coach_team_market
for select to authenticated using (true);

-- Crear una fila de mercat per cada relació entrenador/equip existent.
insert into public.coach_team_market (coach_id, real_team_id, current_value)
select ct.coach_id, ct.real_team_id, 12
from public.coach_teams ct
where not exists (
  select 1 from public.coach_team_market m
  where m.coach_id = ct.coach_id
    and m.real_team_id = ct.real_team_id
);

-- 2) Fórmules de punts i valor dels jugadors.
-- p_win_streak és la ratxa després d'aquesta victòria: 1, 2, 3...
create or replace function public.calculate_player_round_points(
  p_result text,
  p_win_streak integer,
  p_is_highlighted boolean
)
returns numeric
language plpgsql
as $$
declare
  v_multiplier numeric;
  v_points numeric;
begin
  if p_result = 'loss' then
    v_points := 0;
  elsif p_result = 'win' then
    v_multiplier := 1.10 + (p_win_streak * 0.10);
    v_points := 10 * v_multiplier;
  else
    raise exception 'Resultat invàlid: %', p_result;
  end if;

  if p_is_highlighted then
    v_points := v_points + 5;
  end if;

  return v_points;
end;
$$;

create or replace function public.calculate_player_value_change(
  p_result text,
  p_win_streak integer,
  p_is_highlighted boolean
)
returns numeric
language plpgsql
as $$
declare
  v_multiplier numeric;
  v_change numeric;
begin
  if p_result = 'loss' then
    v_change := -4;
  elsif p_result = 'win' then
    v_multiplier := 1.10 + (p_win_streak * 0.10);
    v_change := 7 * v_multiplier;
  else
    raise exception 'Resultat invàlid: %', p_result;
  end if;

  if p_is_highlighted then
    v_change := v_change + 0.5;
  end if;

  return v_change;
end;
$$;

-- 3) Fórmules dels entrenadors.
create or replace function public.calculate_coach_round_points(
  p_result text,
  p_win_streak integer
)
returns numeric
language plpgsql
as $$
declare
  v_multiplier numeric;
begin
  if p_result = 'loss' then
    return 0;
  elsif p_result = 'win' then
    v_multiplier := 1.10 + (p_win_streak * 0.10);
    return 10 * v_multiplier;
  else
    raise exception 'Resultat invàlid: %', p_result;
  end if;
end;
$$;

create or replace function public.calculate_coach_value_change(
  p_result text,
  p_win_streak integer
)
returns numeric
language plpgsql
as $$
declare
  v_multiplier numeric;
begin
  if p_result = 'loss' then
    return -2;
  elsif p_result = 'win' then
    v_multiplier := 1.10 + (p_win_streak * 0.10);
    return 3 * v_multiplier;
  else
    raise exception 'Resultat invàlid: %', p_result;
  end if;
end;
$$;

-- 4) Compra actualitzada: els entrenadors utilitzen el valor del seu equip real.
drop function if exists public.buy_fantasy_asset(bigint,bigint,bigint,bigint,bigint);
create or replace function public.buy_fantasy_asset(
  p_fantasy_team_id bigint,
  p_player_id bigint default null,
  p_coach_id bigint default null,
  p_coach_real_team_id bigint default null,
  p_round_id bigint default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_round_id bigint;
  v_round_number integer;
  v_budget numeric;
  v_price numeric;
  v_commission numeric;
  v_total numeric;
  v_real_team_id bigint;
  v_buys integer;
begin
  if v_user_id is null then raise exception 'Cal iniciar sessió.'; end if;
  if not exists (select 1 from public.fantasy_teams where id=p_fantasy_team_id and owner_id=v_user_id) then
    raise exception 'No pots modificar aquest equip Fantasy.';
  end if;
  if (p_player_id is null) = (p_coach_id is null) then
    raise exception 'Cal indicar un jugador o un entrenador.';
  end if;

  select id, round_number into v_round_id, v_round_number
  from public.fantasy_rounds
  where (p_round_id is null and is_active=true) or id=p_round_id
  order by is_active desc, round_number desc limit 1;
  if v_round_id is null then raise exception 'No hi ha cap jornada activa.'; end if;

  select budget into v_budget from public.fantasy_teams where id=p_fantasy_team_id for update;

  if not (v_round_number = 1 and not exists (select 1 from public.team_round_results where round_id=v_round_id)) then
    select public.count_fantasy_round_buys(p_fantasy_team_id,v_round_id) into v_buys;
    if v_buys >= 2 then raise exception 'Ja has fet els 2 fitxatges màxims d''aquesta jornada.'; end if;
  end if;

  if p_player_id is not null then
    select current_value, real_team_id into v_price, v_real_team_id
    from public.players where id=p_player_id and is_active=true;
    if v_price is null then raise exception 'Jugador no disponible.'; end if;
    if exists (select 1 from public.fantasy_team_players where fantasy_team_id=p_fantasy_team_id and player_id=p_player_id) then raise exception 'Aquest jugador ja és a la plantilla.'; end if;
    if (select count(*) from public.fantasy_team_players ftp join public.players p on p.id=ftp.player_id where ftp.fantasy_team_id=p_fantasy_team_id and p.real_team_id=v_real_team_id) >= 1 then raise exception 'Només pots tenir 1 jugador de cada equip real.'; end if;
    if (select count(*) from public.fantasy_team_players where fantasy_team_id=p_fantasy_team_id) >= 8 then raise exception 'La plantilla ja té 8 jugadors.'; end if;
  else
    if p_coach_real_team_id is null then raise exception 'Cal indicar l''equip real de l''entrenador.'; end if;
    select m.current_value into v_price
    from public.coach_team_market m
    where m.coach_id=p_coach_id and m.real_team_id=p_coach_real_team_id;
    if v_price is null then raise exception 'Entrenador no disponible per a aquest equip.'; end if;
    if not exists (select 1 from public.coach_teams where coach_id=p_coach_id and real_team_id=p_coach_real_team_id) then raise exception 'Aquest entrenador no correspon a aquest equip.'; end if;
    if exists (select 1 from public.fantasy_team_coaches where fantasy_team_id=p_fantasy_team_id and coach_id=p_coach_id and real_team_id=p_coach_real_team_id) then raise exception 'Aquest entrenador ja és a la plantilla.'; end if;
    if (select count(*) from public.fantasy_team_coaches where fantasy_team_id=p_fantasy_team_id) >= 2 then raise exception 'La plantilla ja té 2 entrenadors.'; end if;
  end if;

  v_commission := round(v_price * 0.05,2);
  v_total := v_price + v_commission;
  if v_budget < v_total then raise exception 'No tens prou pressupost. Necessites % i tens %.', v_total, v_budget; end if;

  if p_player_id is not null then
    insert into public.fantasy_team_players(fantasy_team_id,player_id,purchase_value,joined_round_id)
    values(p_fantasy_team_id,p_player_id,v_price,v_round_id);
  else
    insert into public.fantasy_team_coaches(fantasy_team_id,coach_id,real_team_id,purchase_value,joined_round_id)
    values(p_fantasy_team_id,p_coach_id,p_coach_real_team_id,v_price,v_round_id);
  end if;

  update public.fantasy_teams set budget=budget-v_total where id=p_fantasy_team_id;
  insert into public.fantasy_transfers(fantasy_team_id,player_id,coach_id,transfer_type,round_id,market_value,commission,total_cost,real_team_id)
  values(p_fantasy_team_id,p_player_id,p_coach_id,'buy',v_round_id,v_price,v_commission,v_total,p_coach_real_team_id);
end;
$$;
revoke all on function public.buy_fantasy_asset(bigint,bigint,bigint,bigint,bigint) from public;
grant execute on function public.buy_fantasy_asset(bigint,bigint,bigint,bigint,bigint) to authenticated;

-- 5) Venda actualitzada: un entrenador es ven pel valor del seu equip real.
drop function if exists public.sell_fantasy_asset(bigint,bigint,bigint,bigint,bigint);
create or replace function public.sell_fantasy_asset(
  p_fantasy_team_id bigint,
  p_player_id bigint default null,
  p_coach_id bigint default null,
  p_coach_real_team_id bigint default null,
  p_round_id bigint default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_round_id bigint;
  v_price numeric;
  v_real_team_id bigint;
begin
  if v_user_id is null then raise exception 'Cal iniciar sessió.'; end if;
  if not exists (select 1 from public.fantasy_teams where id=p_fantasy_team_id and owner_id=v_user_id) then raise exception 'No pots modificar aquest equip Fantasy.'; end if;
  if (p_player_id is null) = (p_coach_id is null) then raise exception 'Cal indicar un jugador o un entrenador.'; end if;

  select id into v_round_id from public.fantasy_rounds where is_active=true order by round_number desc limit 1;
  if v_round_id is null then raise exception 'No hi ha cap jornada activa.'; end if;

  if p_player_id is not null then
    select p.current_value, p.real_team_id into v_price, v_real_team_id
    from public.fantasy_team_players ftp
    join public.players p on p.id=ftp.player_id
    where ftp.fantasy_team_id=p_fantasy_team_id and ftp.player_id=p_player_id;
    if v_price is null then raise exception 'Aquest jugador no forma part de la teva plantilla.'; end if;
    delete from public.fantasy_team_players where fantasy_team_id=p_fantasy_team_id and player_id=p_player_id;
  else
    select m.current_value, ftc.real_team_id into v_price, v_real_team_id
    from public.fantasy_team_coaches ftc
    join public.coach_team_market m on m.coach_id=ftc.coach_id and m.real_team_id=ftc.real_team_id
    where ftc.fantasy_team_id=p_fantasy_team_id and ftc.coach_id=p_coach_id and ftc.real_team_id=p_coach_real_team_id;
    if v_price is null then raise exception 'Aquest entrenador no forma part de la teva plantilla.'; end if;
    delete from public.fantasy_team_coaches where fantasy_team_id=p_fantasy_team_id and coach_id=p_coach_id and real_team_id=p_coach_real_team_id;
  end if;

  update public.fantasy_teams set budget=budget+v_price where id=p_fantasy_team_id;
  insert into public.fantasy_transfers(fantasy_team_id,player_id,coach_id,transfer_type,round_id,market_value,commission,total_cost,real_team_id)
  values(p_fantasy_team_id,p_player_id,p_coach_id,'sell',v_round_id,v_price,0,v_price,p_coach_real_team_id);
end;
$$;
revoke all on function public.sell_fantasy_asset(bigint,bigint,bigint,bigint,bigint) from public;
grant execute on function public.sell_fantasy_asset(bigint,bigint,bigint,bigint,bigint) to authenticated;

-- 6) Processament de jornada: punts + canvi de valor dels 148 jugadors.
drop function if exists public.process_fantasy_round(bigint);
create or replace function public.process_fantasy_round(p_round_id bigint)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_round_number integer;
  r record;
  v_streak integer;
  v_highlight boolean;
  v_win_points numeric;
  v_highlight_points numeric;
  v_total_points numeric;
  v_change numeric;
  v_new_value numeric;
begin
  select round_number into v_round_number from public.fantasy_rounds where id=p_round_id;
  if v_round_number is null then raise exception 'Jornada no trobada.'; end if;

  for r in
    select p.id as player_id, p.real_team_id, p.current_value, trr.result
    from public.players p
    join public.team_round_results trr
      on trr.round_id=p_round_id and trr.real_team_id=p.real_team_id
    where p.is_active=true
  loop
    if exists (select 1 from public.player_round_history where round_id=p_round_id and player_id=r.player_id) then
      continue;
    end if;

    v_streak := public.get_player_win_streak(r.player_id,v_round_number);
    if r.result='win' then v_streak := v_streak + 1; end if;
    v_highlight := exists(select 1 from public.team_round_highlights where round_id=p_round_id and real_team_id=r.real_team_id and player_id=r.player_id);
    v_win_points := case when r.result='win' then 10 * (1.10 + v_streak*0.10) else 0 end;
    v_highlight_points := case when v_highlight then 5 else 0 end;
    v_total_points := v_win_points + v_highlight_points;
    v_change := public.calculate_player_value_change(r.result,v_streak,v_highlight);
    v_new_value := greatest(0, r.current_value + v_change);

    insert into public.player_round_history(
      round_id,player_id,real_team_id,result,is_highlighted,win_streak,
      win_points,highlight_points,total_points,value_change,value_after
    ) values(
      p_round_id,r.player_id,r.real_team_id,r.result,v_highlight,v_streak,
      v_win_points,v_highlight_points,v_total_points,v_change,v_new_value
    );

    update public.players set current_value=v_new_value where id=r.player_id;
  end loop;
end;
$$;
revoke all on function public.process_fantasy_round(bigint) from public;
grant execute on function public.process_fantasy_round(bigint) to authenticated;

-- 7) Processament de jornada: punts + canvi de valor independent per entrenador/equip.
drop function if exists public.process_coach_round(bigint);
create or replace function public.process_coach_round(p_round_id bigint)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_round_number integer;
  r record;
  v_streak integer;
  v_points numeric;
  v_change numeric;
  v_new_value numeric;
begin
  select round_number into v_round_number from public.fantasy_rounds where id=p_round_id;
  if v_round_number is null then raise exception 'Jornada no trobada.'; end if;

  for r in
    select ct.coach_id, ct.real_team_id, trr.result, m.current_value
    from public.coach_teams ct
    join public.team_round_results trr
      on trr.round_id=p_round_id and trr.real_team_id=ct.real_team_id
    join public.coach_team_market m
      on m.coach_id=ct.coach_id and m.real_team_id=ct.real_team_id
  loop
    if exists (
      select 1 from public.coach_round_history
      where round_id=p_round_id and coach_id=r.coach_id and real_team_id=r.real_team_id
    ) then
      continue;
    end if;

    v_streak := public.get_coach_win_streak(r.coach_id,r.real_team_id,v_round_number);
    if r.result='win' then v_streak := v_streak + 1; end if;
    v_points := public.calculate_coach_round_points(r.result,v_streak);
    v_change := public.calculate_coach_value_change(r.result,v_streak);
    v_new_value := greatest(0,r.current_value+v_change);

    insert into public.coach_round_history(
      round_id,coach_id,real_team_id,result,win_streak,win_points,total_points,value_change,value_after
    ) values(
      p_round_id,r.coach_id,r.real_team_id,r.result,v_streak,v_points,v_points,v_change,v_new_value
    );

    update public.coach_team_market
    set current_value=v_new_value
    where coach_id=r.coach_id and real_team_id=r.real_team_id;
  end loop;
end;
$$;
revoke all on function public.process_coach_round(bigint) from public;
grant execute on function public.process_coach_round(bigint) to authenticated;

-- 8) Retrocedir l'última jornada processada.
-- Només permet retrocedir l'última jornada que tingui historial.
-- Els punts, valors i destacats d'aquella jornada es desfan.
-- Les plantilles i transferències dels usuaris no es toquen.
drop function if exists public.admin_rollback_last_processed_round(text);
create or replace function public.admin_rollback_last_processed_round(p_pin text)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_round_id bigint;
  v_round_number integer;
  v_previous_round_id bigint;
  r record;
begin
  if p_pin <> '1234' then raise exception 'PIN incorrecte.'; end if;

  select id, round_number into v_round_id, v_round_number
  from public.fantasy_rounds fr
  where exists (select 1 from public.player_round_history h where h.round_id=fr.id)
     or exists (select 1 from public.coach_round_history h where h.round_id=fr.id)
  order by fr.round_number desc
  limit 1;

  if v_round_id is null then raise exception 'No hi ha cap jornada processada per retrocedir.'; end if;

  -- No permetem saltar una jornada processada anterior si hi ha dades processades posteriors.
  if exists (
    select 1 from public.fantasy_rounds fr
    where fr.round_number > v_round_number
      and (
        exists (select 1 from public.player_round_history h where h.round_id=fr.id)
        or exists (select 1 from public.coach_round_history h where h.round_id=fr.id)
      )
  ) then
    raise exception 'Només es pot retrocedir l''última jornada processada.';
  end if;

  -- Si hi ha transferències o canvis de capità en una jornada posterior,
  -- no podem moure enrere la jornada sense alterar decisions dels usuaris.
  if exists (
    select 1 from public.fantasy_transfers ft
    join public.fantasy_rounds fr on fr.id=ft.round_id
    where fr.round_number > v_round_number
  ) then
    raise exception 'No es pot retrocedir: hi ha transferències fetes en una jornada posterior.';
  end if;

  if exists (
    select 1 from public.fantasy_team_captain_history ch
    join public.fantasy_rounds fr on fr.id=ch.round_id
    where fr.round_number > v_round_number
  ) then
    raise exception 'No es pot retrocedir: hi ha canvis de capità en una jornada posterior.';
  end if;

  -- Restaurar el valor anterior dels jugadors.
  for r in
    select player_id, value_after, value_change
    from public.player_round_history
    where round_id=v_round_id
  loop
    update public.players
    set current_value = greatest(0, r.value_after - r.value_change)
    where id=r.player_id;
  end loop;

  -- Restaurar el valor anterior dels entrenadors per equip.
  for r in
    select coach_id, real_team_id, value_after, value_change
    from public.coach_round_history
    where round_id=v_round_id
  loop
    update public.coach_team_market
    set current_value = greatest(0, r.value_after - r.value_change)
    where coach_id=r.coach_id and real_team_id=r.real_team_id;
  end loop;

  delete from public.player_round_history where round_id=v_round_id;
  delete from public.coach_round_history where round_id=v_round_id;
  delete from public.team_round_highlights where round_id=v_round_id;
  delete from public.team_round_results where round_id=v_round_id;
  delete from public.fantasy_team_captain_history where round_id=v_round_id;

  -- Recuperar el capità de la jornada anterior, si n'hi havia.
  update public.fantasy_team_players set is_captain=false;
  select id into v_previous_round_id
  from public.fantasy_rounds
  where round_number < v_round_number
  order by round_number desc
  limit 1;

  if v_previous_round_id is not null then
    update public.fantasy_team_players ftp
    set is_captain=true
    from public.fantasy_team_captain_history ch
    where ch.round_id=v_previous_round_id
      and ch.fantasy_team_id=ftp.fantasy_team_id
      and ch.player_id=ftp.player_id;
  end if;

  -- La jornada retrocedida torna a ser l'activa.
  update public.fantasy_rounds set is_active=false;
  update public.fantasy_rounds set is_active=true where id=v_round_id;

  -- Les jornades posteriors sense historial/resultats/transferències es poden eliminar.
  delete from public.fantasy_rounds fr
  where fr.round_number > v_round_number
    and not exists (select 1 from public.player_round_history h where h.round_id=fr.id)
    and not exists (select 1 from public.coach_round_history h where h.round_id=fr.id)
    and not exists (select 1 from public.team_round_results h where h.round_id=fr.id)
    and not exists (select 1 from public.team_round_highlights h where h.round_id=fr.id)
    and not exists (select 1 from public.fantasy_transfers h where h.round_id=fr.id)
    and not exists (select 1 from public.fantasy_team_captain_history h where h.round_id=fr.id);
end;
$$;
revoke all on function public.admin_rollback_last_processed_round(text) from public;
grant execute on function public.admin_rollback_last_processed_round(text) to authenticated;

-- 9) Reset complet també reinicia el mercat independent dels entrenadors.
create or replace function public.admin_reset_rounds(p_pin text)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if p_pin <> '1234' then raise exception 'PIN incorrecte.'; end if;
  delete from public.fantasy_transfers;
  delete from public.player_round_history;
  delete from public.coach_round_history;
  delete from public.team_round_highlights;
  delete from public.team_round_results;
  delete from public.fantasy_team_captain_history;
  delete from public.fantasy_team_players;
  delete from public.fantasy_team_coaches;
  update public.players set current_value=10;
  update public.coaches set current_value=12;
  update public.coach_team_market set current_value=12;
  update public.fantasy_teams set budget=120;
  delete from public.fantasy_rounds where round_number > 1;
  update public.fantasy_rounds set is_active=(round_number=1), name='Jornada 1' where round_number=1;
end;
$$;
revoke all on function public.admin_reset_rounds(text) from public;
grant execute on function public.admin_reset_rounds(text) to authenticated;
